[project]
name = "atlottery"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyinstaller>=6.14.2",
    "pyside6>=6.9.1",
    "selenium>=4.34.0",
    "webdriver-manager>=4.0.2",
]
