name: Build and Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Release tag (e.g. v1.0.0)"
        required: true
        default: "v1.0.0"

permissions:
  contents: write

jobs:
  build-release:
  
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
        
    - name: Install uv
      run: |
        python -m pip install --upgrade pip
        pip install uv
    - name: Sync dependencies with uv
      run: |
        uv sync
    - name: Build with PyInstaller
      run: uv run pyinstaller atlottery.spec
        
    - name: Archive build output
      run: |
        mkdir release
        xcopy /E /I dist release
        Compress-Archive -Path release\* -DestinationPath atlottery.zip
    - name: Upload Release to GitHub
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.event.inputs.tag_name }}
        files: atlottery.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
