name: exe-build-release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Release tag (e.g. v1.0.0)"
        required: true
        default: "v1.0.0"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install uv and Sync dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv sync

      - name: Build with pyinstaller
        run: uv run pyinstaller atlottery.spec

      - name: Archive release file
        run: |
          mkdir release
          xcopy /E /I dist release
          Compress-Archive -Path release\* -DestinationPath atlottery.zip

      - name: Upload archive file
        uses: actions/upload-artifact@v4
        with:
          name: release-file
          path: atlottery.zip


  release:
    runs-on: windows-latest
    needs:
      - build
    permissions:
      id-token: write

    environment:
      name: pypi

    steps:
      - name: Retrieve release file
        uses: actions/download-artifact@v4
        with:
          name: release-file
          path: atlottery.zip

      - name: Release to GitHub
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          files: atlottery.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
